plugins {
    id("base-conventions")
    id("game-cache-test-conventions")
}

dependencies {
    implementation(projects.api.pluginCommons)
    implementation(projects.api.attr)
    implementation(projects.api.registry)
    implementation(projects.api.combat.combatManager)
    implementation(projects.api.spells)
    implementation(projects.content.skills.crafting)
    implementation(projects.content.skills.utils)
    implementation(projects.content.quest)
    implementation(projects.content.generic.genericLocs)
    implementation(projects.content.other.consumables)
    implementation(projects.api.combat.combatCommons)
    implementation(projects.api.death)
    implementation(projects.api.npc)
    implementation(projects.content.travel.jewellery)
    implementation(projects.api.spellsAutocast)
    implementation(projects.api.mechanics.toxins)
    implementation(projects.content.other.pets)
    implementation(projects.content.interfaces.emotes)
    implementation(projects.content.interfaces.bank)
    implementation(projects.api.combat.combatWeapon)
    implementation(projects.api.combatMaxhit)
    implementation(projects.api.invtx)
    implementation(projects.api.areaChecker)
    implementation(projects.api.net)
    implementation(projects.api.db)
    implementation(projects.api.dbGateway)
    implementation(projects.content.areas.wilderness)
    testImplementation(libs.fastutil)
}
