[[varp]]
id = "varp.castlewars_lanthus"
scope = "Perm"
transmit = "Never"

[[varbit]]
id = "varbit.castlewars_xp_disabled"
varp = "varp.castlewars_lanthus"
startBit = 0
endBit = 0

[[varbit]]
id = "varbit.castlewars_bracelet_charges"
varp = "varp.castlewars_lanthus"
startBit = 1
endBit = 10

[[varbit]]
id = "varbit.castlewars_bracelet_paused"
varp = "varp.castlewars_lanthus"
startBit = 11
endBit = 11

[[varbit]]
id = "varbit.castlewars_bracelet_active"
varp = "varp.castlewars_lanthus"
startBit = 12
endBit = 12

[[varbit]]
id = "varbit.castlewars_tools_recorded"
varp = "varp.castlewars_lanthus"
startBit = 13
endBit = 13

[[varbit]]
id = "varbit.castlewars_brought_tinderboxes"
varp = "varp.castlewars_lanthus"
startBit = 14
endBit = 18

[[varbit]]
id = "varbit.castlewars_brought_pickaxes"
varp = "varp.castlewars_lanthus"
startBit = 19
endBit = 23

[[varbit]]
id = "varbit.castlewars_brought_buckets"
varp = "varp.castlewars_lanthus"
startBit = 24
endBit = 28

[[npc]]
id = "npc.castlewars_barricade_saradomin_render_under"
inherit = "npc.castlewars_barricade_saradomin_render_under"
moveRestrict = "NoMove"
blockWalk = "All"

[[npc]]
id = "npc.castlewars_barricade_burning_saradomin_render_under"
inherit = "npc.castlewars_barricade_burning_saradomin_render_under"
moveRestrict = "NoMove"
blockWalk = "All"

[[npc]]
id = "npc.castlewars_barricade_zamorak_render_under"
inherit = "npc.castlewars_barricade_zamorak_render_under"
moveRestrict = "NoMove"
blockWalk = "All"

[[npc]]
id = "npc.castlewars_barricade_burning_zamorak_render_under"
inherit = "npc.castlewars_barricade_burning_zamorak_render_under"
moveRestrict = "NoMove"
blockWalk = "All"
