# The inside of Grum's Gold Exchange in Port Sarim. During Merlin's Crystal the beggar the Lady
# of the Lake sent the player to meet comes over and asks for bread as soon as they walk in.
[[area]]
name = "Merlin's Crystal Port Sarim jeweller"
area_id = "area.merlin_sarim_jeweller"
levels = [0]

[[area.polygons]]
vertices = [
    [3011, 3244],
    [3016, 3244],
    [3016, 3250],
    [3011, 3250],
]
